trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'  # JDK version
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    installationDirectory: $(Agent.ToolsDirectory)/jdk


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: 'Container'
