trigger:
  branches:
    include:
    - main  # Only trigger for changes in main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    installationDirectory: $(Agent.ToolsDirectory)/jdk

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: 'Container'
